// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKxgk8SfXxVaTvL6QqIA28tDe6IWrY4VQ',
    appId: '1:610410248260:web:b9beaf73866aabad80a411',
    messagingSenderId: '610410248260',
    projectId: 'flutter-chat-926f1',
    authDomain: 'flutter-chat-926f1.firebaseapp.com',
    storageBucket: 'flutter-chat-926f1.appspot.com',
    measurementId: 'G-0RBBGXH2CK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcVdjNNETbwLofHyuEocdg3c33Go2vsnU',
    appId: '1:610410248260:android:e013b3583a97f20080a411',
    messagingSenderId: '610410248260',
    projectId: 'flutter-chat-926f1',
    storageBucket: 'flutter-chat-926f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAeA-8pIynm3eoyfIc7ugoiVF4pg8jSiA',
    appId: '1:610410248260:ios:70b6f1edf6cec89d80a411',
    messagingSenderId: '610410248260',
    projectId: 'flutter-chat-926f1',
    storageBucket: 'flutter-chat-926f1.appspot.com',
    androidClientId: '610410248260-78es2kr9d5q2mekstoq4is95gbulq3gv.apps.googleusercontent.com',
    iosClientId: '610410248260-9ojaqdhd9csr2hraj92tuo7mbpc5u6o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterchat',
  );
}
